### ISSUE TITLE
eclipselink/README contains wrong package names

### ISSUE THREAD

**Issue by gerrit-hohl** [jipijapa/jipijapa#9]
Hello,

I saw that your project is (maybe) a fork of this one here: [as7-eclipselink-integration](https://github.com/ringerc/as7-eclipselink-integration)
Maybe that is the reason why your README file contains still the package names from that time:
> $JBOSS_HOME/bin/jboss-cli.sh --connect
> 
>   /system-property=eclipselink.target-server:add(value=JBoss)
>   /system-property=eclipselink.logging.logger:add(value=id.au.ringerc.as7.eclipselinkintegration.JBossLogger)
>   /system-property=eclipselink.archive.factory:add(value=id.au.ringerc.as7.eclipselinkintegration.JBossArchiveFactoryImpl)

Shouldn't that be:
> $JBOSS_HOME/bin/jboss-cli.sh --connect
> 
>   /system-property=eclipselink.target-server:add(value=JBoss)
>   /system-property=eclipselink.logging.logger:add(value=org.jipijapa.eclipselink.JBossLogger)
>   /system-property=eclipselink.archive.factory:add(value=org.jipijapa.eclipselink.JBossArchiveFactoryImpl)

**Comment by gerrit-hohl** [comment]
Seems the moved code doesn't have any README anymore: [WildFly EclipseLink](https://github.com/wildfly/wildfly/tree/master/jpa/eclipselink)

**Comment by scottmarlow** [comment]
Some of the (JPA) integration code started out in the JBoss application server source and later became a separate project via https://github.com/jipijapa/jipijapa, which was only consumed by the JBoss application server (now renamed to WildFly).  To get more eyes on the integration code (besides mine), it was then moved back to the app server https://github.com/wildfly/wildfly/tree/master/jpa (or https://github.com/wildfly/wildfly/tree/master/jpa/eclipselink).

I agree that value=id.au.ringerc.as7.eclipselinkintegration.JBossLogger is wrong, it was left over from the original contribution https://github.com/ringerc/as7-eclipselink-integration ("Integration code for using EclipseLink on JBoss AS 7, mostly a packaged and tested version of code by Rich DiCroce. Credit is his, bugs are probably mine. https://community.jboss.org/wiki/HowToUseEclipseLinkWithAS7").

Some user documentation on using EclipseLink + WildFly is at https://docs.jboss.org/author/display/WFLY/JPA+Reference+Guide#JPAReferenceGuide-UsingEclipseLink, updates welcome, as well as patches for the https://github.com/wildfly/wildfly/tree/master/jpa code. :-)

**Comment by gerrit-hohl** [comment]
Thanks, @scottmarlow 😃 

About that reference guide link you posted I have a question. That guide describes how I have to add jipijapa-eclipselink to WildFly. But it is already part of WildFly-10.1.0.Final (Located at `wildfly-10.1.0.Final\modules\system\layers\base\org\eclipse\persistence\main`; named `jipijapa-eclipselink-10.1.0.Final.jar` and having a corresponding `module.xml` in the same folder). Still it seems that classes from that JAR can't be found when the persistence.xml is read by WildFly (E.g. the `org.jipijapa.eclipselink.JBossArchiveFactoryImpl`):

`Failed to define class org.jipijapa.eclipselink.JBossArchiveFactoryImpl in Module "org.eclipse.persistence:main" from local module loader`

It even shows the right module name also I didn't specify anything. So it seems that it somehow knows how to load that class, but doesn't find it - also it is definitely part of the corresponding JAR archive (I looked it up in the module folder of WildFly).

Any idea on that?

**Comment by gerrit-hohl** [comment]
Okay, found my problem (see [Re: WildFly & Arquillian & EclipseLink: jipijapa-eclipselink classes can't be found during deployment](https://developer.jboss.org/message/965804#965804)). The problem was not the jipijapa-eclipselink, but the eclipselink. Don't know why that error message is so misleading. 😞
